Controllers/EmojiController.cs
using Discord.WebSocket;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RomDiscord.Models.Db;
using RomDiscord.Services;
using RomDiscord.Util;

namespace RomDiscord.Controllers
{

	[Route("[controller]")]
	[Controller]
	public class EmojiController : Controller
	{
		private readonly ModuleSettings settings;
		private readonly DiscordSocketClient discord;
		private readonly Context context;

		public EmojiController(ModuleSettings settings, DiscordSocketClient discord, Context context)
		{
			this.settings = settings;
			this.discord = discord;
			this.context = context;
		}

		public IActionResult Index()
		{
			var guild = this.Guild(context);
			if (guild == null)
				return RedirectToAction("Index", "Home");
			return View(new RomDiscord.Models.Pages.Emoji.Index()
			{
				Emoji = discord.Guilds.First(g => g.Id == guild?.DiscordGuildId).Emotes,
				Settings = settings,
				Guild = guild
			});
		}

		[HttpPost("UpdateJobEmoji/{job}/{emoji}")]
		public async Task<IActionResult> UpdateJobEmoji(Job job, ulong emoji)
		{
			var guild = this.Guild(context);
			if (guild == null)
				return RedirectToAction("Index", "Home");
			await settings.Set(guild, "emoji", job.ToString(), emoji + "");
			return Ok("Ok");
		}

	}
}

Controllers/ExchangeController.cs
using Discord.WebSocket;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RomDiscord.Models.Db;
using RomDiscord.Models.Pages.Exchange;
using RomDiscord.Services;
using RomDiscord.Util;
using System.Threading.Channels;

namespace RomDiscord.Controllers
{

	[Route("[controller]")]
	[Controller]
	public class ExchangeController : Controller
	{
		private readonly ModuleSettings settings;
		private readonly DiscordSocketClient discord;
		private readonly Context context;
		private readonly ItemDb itemDb;

		public ExchangeController(ModuleSettings settings, DiscordSocketClient discord, Context context, ItemDb itemDb)
		{
			this.settings = settings;
			this.discord = discord;
			this.context = context;
			this.itemDb = itemDb;
		}

		public IActionResult Index()
		{
			var guild = this.Guild(context);
			if (guild == null)
				return RedirectToAction("Index", "Home");
			var dcGuild = discord.Guilds.First(g => g.Id == guild.DiscordGuildId);
			return View(new Models.Pages.Exchange.Index()
			{
				Settings = new SettingsModel(settings, guild),
				Guild = guild,
				Channels = dcGuild.TextChannels.OrderBy(c => c.Position).ToList(),
				PublicNotifications = context.ExchangePublicNotifications.Where(n => n.Guild == guild).ToList().GroupBy(g => g.ChannelId, g => g).ToDictionary(g => g.Key, g => g.OrderBy(g => g.ItemId).ToList()),
				ItemDb = itemDb
			});
		}

		[HttpPost("AddItem")]
		public async Task<IActionResult> AddItem(int ItemId, ulong ChannelId)
		{
			var guild = this.Guild(context);
			if (guild == null)
				return RedirectToAction("Index", "Home");
			await settings.Set(guild, "exchange", "lastChannel", ChannelId + "");

			context.ExchangePublicNotifications.Add(new ExchangePublicNotification()
			{
				ItemId = ItemId,
				ChannelId = ChannelId,
				Guild = guild
			});
			await context.SaveChangesAsync();
			return RedirectToAction("Index");
		}


		[HttpPost("ChangeChannel/{notificationId}/{channelId}")]
		public async Task<IActionResult> ChangeChannel(int notificationId, ulong channelId)
		{
			var guild = this.Guild(context);
			if (guild == null)
				return RedirectToAction("Index", "Home");
			var notification = await context.ExchangePublicNotifications.FindAsync(notificationId);
			if(notification != null)
				notification.ChannelId = channelId;
			await context.SaveChangesAsync();
			return Ok("ok");
		}

		[HttpPost("UpdatePublicNotification")]
		public async Task<IActionResult> UpdatePublicNotification(int Id, int MinRefineLevel, int Enchant, int MinEnchantLevel, string Action)
		{
            var guild = this.Guild(context);
            if (guild == null)
                return RedirectToAction("Index", "Home");
            var notification = await context.ExchangePublicNotifications.FindAsync(Id);
			if (Action == "Delete")
			{
				context.ExchangePublicNotifications.Remove(notification);
			}
			else
			{
				if (notification != null)
				{
					notification.MinRefineLevel = MinRefineLevel;
					notification.Enchant = (Enchant)Enchant;
					notification.MinEnchantLevel = MinEnchantLevel;
				}
			}
            await context.SaveChangesAsync();

            return RedirectToAction("Index");
        }


    }
}

Controllers/MembersController.cs
using Discord.WebSocket;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RomDiscord.Models.Db;
using RomDiscord.Models.Pages.Members;
using RomDiscord.Util;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace RomDiscord.Controllers
{
	[Route("[controller]")]
	[Controller]
	public class MembersController : Controller
	{
		private readonly Context context;
		private readonly DiscordSocketClient discord;

		public MembersController(Context context, DiscordSocketClient discord)
		{
			this.context = context;
			this.discord = discord;
		}

		[HttpGet]
		public async Task<IActionResult> Index()
		{
			var guild = this.Guild(context);
			if(guild == null)
				return RedirectToAction("Index", "Home");
			var model = new Models.Pages.Members.Index()
			{
				Members = await context.Members.Where(m => m.Guild == guild).ToListAsync(),
				DiscordMembers = discord.Guilds.First(g => g.Id == guild.DiscordGuildId).Users.ToList()
			};

			return View(model);
		}

		[HttpGet("Edit/{memberId}")]
		public async Task<IActionResult> Edit(int memberId)
		{
			var guild = this.Guild(context);
			if (guild == null)
				return RedirectToAction("Index", "Home");
			var model = new Models.Pages.Members.EditModel()
			{
				Member = await context.Members.FirstAsync(m => m.MemberId == memberId),
				DiscordMembers = discord.Guilds.First(g => g.Id == guild.DiscordGuildId).Users.ToList()
			};
			return View(model);
		}

		[HttpGet("Stats")]
		public async Task<IActionResult> Stats()
		{
			var guild = this.Guild(context);
			return View(await context.Members.Where(m => m.Guild == guild).ToListAsync());
		}

		[HttpPost("AddMember")]
		public async Task<IActionResult> AddMember([FromForm]AddMemberModel data)
		{
			var guild = this.Guild(context);
			if (guild == null)
				return RedirectToAction("Index", "Home");
			var dc = discord.Guilds.FirstOrDefault(g => g.Id == guild.DiscordGuildId);
			SocketGuildUser? dcUser = null;
			if(dc != null)
				dcUser = dc.Users.FirstOrDefault(u => u.Id == data.DiscordId);
			context.Members.Add(new Member()
			{
				Name = data.Name,
				Guild = guild,
				DiscordId = data.DiscordId,
				DiscordName = dcUser == null ? "" : (dcUser.Username + "#" + dcUser.Discriminator),
				AlternativeNames = "",
				Jobs = "",
				ShortNote = "",
				LongNote = "",
			});
			await context.SaveChangesAsync();
			return RedirectToAction("Index");
		}

		[HttpPost("Left/{memberId}")]
		public async Task<IActionResult> Left(int memberId)
		{
			var member = context.Members.First(m => m.MemberId == memberId);
			var guild = this.Guild(context);
			if (guild == null)
				return RedirectToAction("Index", "Home");

			member.Active = false;

			await context.SaveChangesAsync();

			return RedirectToAction("Index");
		}

		[HttpPost("Back/{memberId}")]
		public async Task<IActionResult> Back(int memberId)
		{
			var member = context.Members.First(m => m.MemberId == memberId);
			var guild = this.Guild(context);
			if (guild == null)
				return RedirectToAction("Index", "Home");

			member.Active = true;

			await context.SaveChangesAsync();

			return RedirectToAction("Index");
		}

		[HttpPost("Update/{memberId}")]
		public async Task<IActionResult> UpdateMember(int memberId, [FromForm]UpdateMemberModel data)
		{
			var member = context.Members.First(m => m.MemberId == memberId);
			var guild = this.Guild(context);
			if (guild == null)
				return RedirectToAction("Index", "Home");

			member.Name = data.Name;
			member.ShortNote = data.ShortNote;
			member.LongNote = data.LongNote;
			member.JoinDate = data.JoinDate;
			member.AlternativeNames = data.AlternativeNames ?? "";
			//member.JobList = data.Jobs;
			if (data.Jobs != null)
				member.Jobs = String.Join(",", data.Jobs);

			member.DiscordId = data.DiscordId;
			var dc = discord.Guilds.FirstOrDefault(g => g.Id == guild.DiscordGuildId);
			SocketGuildUser? dcUser = null;
			if (dc != null)
				dcUser = dc.Users.FirstOrDefault(u => u.Id == data.DiscordId);
			if (dcUser != null)
				member.DiscordName = dcUser.Username + "#" + dcUser.Discriminator;

			await context.SaveChangesAsync();

			return RedirectToAction("Index");
		}

		[HttpPost("checkjson")]
		[Produces("text/plain")]
		public async Task<IActionResult> CheckJson([FromForm] string jsondata)
		{
			var guild = this.Guild(context);
			if (guild == null)
				return RedirectToAction("Index", "Home");
			var dc = discord.Guilds.FirstOrDefault(g => g.Id == guild.DiscordGuildId);

			JsonNode json = JsonSerializer.Deserialize<JsonNode>(jsondata) ?? new JsonObject();

			List<string> ingameNames = new List<string>();
			string data = "";
			data += "Ingame Members: \n";
			foreach (var member in json?["data"]?["members"]?.AsArray())
			{
				string name = member?["name"]?.GetValue<string>()?.Replace("\u0002", "") ?? "";
				data += name + "\n";
				ingameNames.Add(name);
			}
			data += "\n\n";

			List<SocketGuildUser> dcMembers = new List<SocketGuildUser>();
			data += "People with guild-member role: \n";
			foreach (var dcMember in dc?.Roles?.First(g => g.Id == 819475701232959528)?.Members ?? new List<SocketGuildUser>())
			{
				data += dcMember.DisplayName + "\n";
				dcMembers.Add(dcMember);
			}

			var members = context.Members.Where(m => m.Guild == guild && m.Active).ToList();
			foreach(var member in members)
			{
				if (!ingameNames.Any(n => n == member.Name))
					data += "Registry: user " + member.Name + " is not found ingame!\n";
				if (member.DiscordId != 0 && !dcMembers.Any(m => m.Id == member.DiscordId))
					data += "Registry: user " + member.Name + " does not have the proper role in discord!\n";
				if (member.DiscordId == 0)
					data += "Registry: user " + member.Name + " is not on discord\n";
			}

			foreach(var dcMember in dcMembers)
			{
				if (!members.Any(m => m.DiscordId == dcMember.Id))
					data += "Discord: user " + dcMember.DisplayName + " has guildmember role, but is not in the registry\n";
			}
			foreach (var name in ingameNames)
			{
				if (!members.Any(m => m.Name == name))
					data += "Ingame: user " + name + " is in the guild ingame, but is not in the registry\n";
			}

			return Content(data);

		}
	}
}

Controllers/MvpHuntController.cs
using Discord.WebSocket;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RomDiscord.Models.Db;
using RomDiscord.Services;
using RomDiscord.Util;

namespace RomDiscord.Controllers
{

	[Route("[controller]")]
	[Controller]
	public class MvpHuntController : Controller
	{
		private readonly ModuleSettings settings;
		private readonly DiscordSocketClient discord;
		private readonly Context context;

		public MvpHuntController(ModuleSettings settings, DiscordSocketClient discord, Context context)
		{
			this.settings = settings;
			this.discord = discord;
			this.context = context;
		}

		public IActionResult Index()
		{
			var guild = this.Guild(context);
			if (guild == null)
				return RedirectToAction("Index", "Home");
			var dcGuild = discord.Guilds.First(g => g.Id == guild.DiscordGuildId);
			return View(new Models.Pages.MvpHunt.Index()
			{
				Settings = settings,
				Guild = guild,
				Channels = dcGuild.TextChannels.OrderBy(c => c.Position).ToList()
			});
		}

		[HttpPost("UpdateChannel/{channel}/{dcChannel}")]
		public async Task<IActionResult> UpdateChannel(string channel, ulong dcChannel)
		{
			var guild = this.Guild(context);
			if (guild == null)
				return RedirectToAction("Index", "Home");
			await settings.Set(guild, "mvphunt", channel, dcChannel + "");
			return Ok("Ok");
		}

	}
}

Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>ROM Discord Bot Manager</title>
    <style>
        
        @@media (max-width: 992px)
        {
            #leftbar
            {
                display: none;
            }
            #leftbar.show
            {
                display: block !important;
            }
        }
        @@media (min-width: 992px)
        {
            #leftbar
            {
                display: block !important;
            }
        }



        .leftbar .feather {
            width: 16px;
            height: 16px;
            margin-right: 5px;
            vertical-align: text-bottom;
        }

        .guildpickerlist img {
            height: 32px;
            width: auto;
            margin-right: 10px;
        }
        .nav-sub
        {
            margin-left: 20px;
        }



    </style>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js" integrity="sha256-eTyxS0rkjpLEo16uXTS0uVCS4815lc40K2iVpWDvdSY=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha256-YvdLHPgkqJ8DVUxjjnGVlMMJtNimJ6dYkowFFvp4kKs=" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha256-9SEPo+fwJFpMUet/KACSwO+Z/dKMReF9q4zFhU/fT9M=" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/feather-icons@4.28.0/dist/feather.min.js"></script>
    <script src="/js/bootstrap-autocomplete.js"></script>
    <script>
        $.postJSON = function (url, data, callback) {
            return jQuery.ajax({
                'type': 'POST',
                'url': url,
                'contentType': 'application/json',
                'data': JSON.stringify(data),
                'dataType': 'json',
                'success': callback
            });
        };
    </script>
  </head>
  <body class="bg-dark text-white">
    <div class="border-bottom" style="margin-bottom: 100px;">
    <partial name="_TopBar"/>
    </div>
    <div style="display: flex; flex-wrap: nowrap; ">

        <div id="leftbar" class="collapse-horizontal flex-column flex-shrink-0 p-3 text-white bg-dark border-right leftbar collapse" style="height: 100%">
            <div style="width: 200px; overflow: hidden;">
            <partial name="_LeftBar"/>
            </div>
        </div>
        <div class="container d-flex flex-column overflow-y: auto; height: 100vh; min-width: 600px;">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
    <script>
        feather.replace()
        $('[data-toggle="tooltip"]').tooltip();
        $(function()
        {
            $('.itemListComplete').autoComplete({
                resolverSettings: {
                    url: '/api/Items/'
                }
            });
            $('.channelListComplete').autoComplete({
                resolverSettings: {
                    url: '/api/Channels/'
                }
            });
        });
    </script>
  </body>
</html>

Views/Shared/_LeftBar.cshtml
@{
}

<ul class="nav nav-pills flex-column mb-auto">
@if((User.Identity?.IsAuthenticated ?? false) && Context.SessionData != null && Context.SessionData().ActiveGuild != null)
{
    <li class="nav-item"><a asp-controller="Home" asp-action="Index" class="nav-link @Html.ActiveClass("Home")" aria-current="page"><span data-feather="home"></span>Home</a></li>
    <li class="nav-item"><a asp-controller="Weeklies" asp-action="Index" class="nav-link @Html.ActiveClass("Weeklies", null, "active", "text-secondary")" aria-current="page"><span data-feather="calendar"></span>Weeklies</a></li>
    <li class="nav-item"><a asp-controller="GodRaffle" asp-action="Index" class="nav-link @Html.ActiveClass("GodRaffle", "Index")" aria-current="page"><span data-feather="shield"></span>God Equip Raffle</a></li>
    @if (Html.ViewContext.RouteData.Values["controller"]?.ToString() == "GodRaffle")
    {
        <li class="nav-item nav-sub"><a asp-controller="GodRaffle" asp-action="CalendarMonth" class="nav-link @Html.ActiveClass("GodRaffle","CalendarMonth")" aria-current="page"><span data-feather="calendar"></span>Calendar (month)</a></li>
        <li class="nav-item nav-sub"><a asp-controller="GodRaffle" asp-action="CalendarWeek" class="nav-link @Html.ActiveClass("GodRaffle","CalendarWeek")" aria-current="page"><span data-feather="calendar"></span>Calendar (week)</a></li>
    }
    <li class="nav-item"><a href="#" class="nav-link text-secondary" aria-current="page"><span data-feather="zap"></span>Popup PVP</a></li>
    <li class="nav-item"><a asp-controller="Events" asp-action="Index" class="nav-link @Html.ActiveClass("Events")" aria-current="page"><span data-feather="calendar"></span>Events</a></li>
    <li class="nav-item"><a href="#" class="nav-link text-secondary" aria-current="page"><span data-feather="box"></span>Items</a></li>
    <li class="nav-item"><a href="#" class="nav-link text-secondary" aria-current="page"><span data-feather="smile"></span>Mobs</a></li>
    <li class="nav-item"><a asp-controller="MvpHunt" asp-action="Index" class="nav-link @Html.ActiveClass("MvpHunt", "Index")" aria-current="page"><span data-feather="crosshair"></span>MVP Hunters</a></li>
    <li class="nav-item"><a asp-controller="Exchange" asp-action="Index" class="nav-link @Html.ActiveClass("Exchange", "Index")" aria-current="page"><span data-feather="dollar-sign"></span>Exchange</a></li>
    <hr/>
    <li class="nav-item"><a asp-controller="Members" asp-action="Index" class="nav-link @Html.ActiveClass("Members", "Index")" aria-current="page"><span data-feather="user"></span>Members</a></li>
    @if(Html.ViewContext.RouteData.Values["controller"]?.ToString() == "Members")
    {
        <li class="nav-item nav-sub"><a asp-controller="Members" asp-action="Stats" class="nav-link @Html.ActiveClass("Members","Stats")" aria-current="page"><span data-feather="pie-chart"></span>Stats</a></li>
    }
    <li class="nav-item"><a asp-controller="Attendance" asp-action="Index" class="nav-link @Html.ActiveClass("Attendance", "Index")" aria-current="page"><span data-feather="user-check"></span>Attendance</a></li>
    @if (Html.ViewContext.RouteData.Values["controller"]?.ToString() == "Attendance")
    {
        <li class="nav-item nav-sub"><a asp-controller="Attendance" asp-action="Stats" class="nav-link @Html.ActiveClass("Attendance","Stats")" aria-current="page"><span data-feather="pie-chart"></span>Stats (overall)</a></li>
        <li class="nav-item nav-sub"><a asp-controller="Attendance" asp-action="StatsMember" class="nav-link @Html.ActiveClass("Attendance","StatsMember")" aria-current="page"><span data-feather="pie-chart"></span>Stats (per member)</a></li>
    }
    <li class="nav-item"><a asp-controller="Party" asp-action="Index" class="nav-link @Html.ActiveClass("Party", "Index")" aria-current="page"><span data-feather="users"></span>Parties</a></li>
    <li class="nav-item"><a asp-controller="Emoji" asp-action="Index" class="nav-link @Html.ActiveClass("Emoji", "Index")" aria-current="page"><span data-feather="smile"></span>Emoji</a></li>
    <li class="nav-item"><a asp-controller="Handbook" asp-action="Index" class="nav-link @Html.ActiveClass("Handbook", "Index")" aria-current="page"><span data-feather="book"></span>Handbook</a></li>
    <li class="nav-item"><a asp-controller="GameChat" asp-action="Index" class="nav-link @Html.ActiveClass("GameChat", "Index")" aria-current="page"><span data-feather="message-circle"></span>Ingame Chat</a></li>
    <hr/>
    <li class="nav-item"><a asp-controller="Quiz" asp-action="Index" class="nav-link text-white" aria-current="page"><span data-feather="help-circle"></span>Quiz</a></li>
    <li class="nav-item"><a href="#" class="nav-link text-secondary" aria-current="page"><span data-feather="settings"></span>Custom Commands</a></li>
    <li class="nav-item"><a href="#" class="nav-link text-secondary" aria-current="page"><span data-feather="lock"></span>Auto role Assignment</a></li>
}
else
{
    <li class="nav-item active"></li>
}
</ul>

Views/Shared/_TopBar.cshtml
@{
}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark text-light fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rom Discord Bot Management</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#leftbar" aria-controls="leftbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                </li>
                @if ((User.Identity?.IsAuthenticated ?? false) && Context.SessionData != null)
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            @if (Context.SessionData().ActiveGuild == null)
                            {
                                <span>No Guild</span>
                            }
                            else
                            {
                                <span><img style="height: 32px; width: auto; margin-right: 10px;" src="https://cdn.discordapp.com/icons/@Context.SessionData()?.ActiveGuild?.Id/@(Context.SessionData().ActiveGuild?.Icon).png">@Context.SessionData().ActiveGuild?.Name</span>
                            }
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-dark guildpickerlist" aria-labelledby="navbarDropdown">
                            @foreach (var guild in Context.SessionData().Guilds)
                            {
                                <li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="SwitchServer" asp-route-id="@(guild.Id)"><img src="https://cdn.discordapp.com/icons/@guild.Id/@(guild.Icon).png">@guild.Name</a></li>
                            }
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" asp-controller="home" asp-action="Logout">Logout</a></li>
                        </ul>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                    </li>
                }
            </ul>
        </div>
    </div>
</nav>